swagger: '2.0'
info:
  title: DORA Publications MCP Server
  description: Model Context Protocol server for searching DORA (Digital Object Repository for Academia) scientific publications
  version: 1.0.0
host: dora-mcp-xrtnba.fly.dev
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: DORA Publications Search Server
      description: |
        MCP Streamable endpoint for searching scientific publications.
        
        Example request bodies:
        
        1. Initialize the connection:
        ```json
        {
          "jsonrpc": "2.0",
          "id": 1,
          "method": "initialize",
          "params": {
            "protocolVersion": "2024-11-05",
            "capabilities": {},
            "clientInfo": {
              "name": "test-client",
              "version": "1.0.0"
            }
          }
        }
        ```
        
        2. List available tools:
        ```json
        {
          "jsonrpc": "2.0",
          "id": 2,
          "method": "tools/list"
        }
        ```
        
        3. Search for publications:
        ```json
        {
          "jsonrpc": "2.0",
          "id": 3,
          "method": "tools/call",
          "params": {
            "name": "search_publications",
            "arguments": {
              "search_string": "machine learning",
              "limit": 5
            }
          }
        }
        ```
      operationId: InvokeMCP
      x-ms-agentic-protocol: mcp-streamable-1.0
      x-ms-agentic-tools:
        - name: search_publications
          description: Search the DORA (Digital Object Repository for Academia) database for scientific publications. Searches across titles, abstracts, authors, and other metadata fields. IMPORTANT - Use SHORT KEYWORDS or AUTHOR NAMES only, not long phrases or sentences. Examples - 'climate change', 'machine learning', 'John Smith'. Avoid full sentences or questions.
          inputSchema:
            type: object
            properties:
              search_string:
                type: string
                description: SHORT search keywords or author name (1-3 keywords maximum). Good examples - 'manfred heuberger', 'polymer coating', 'tribology'. Bad examples - 'find papers about machine learning'.
            required:
              - search_string
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Success
          examples:
            application/json:
              jsonrpc: "2.0"
              id: 1
              result:
                protocolVersion: "2024-11-05"
                serverInfo:
                  name: "dora-mcp-server"
                  version: "1.0.0"
securityDefinitions: {}
security: []
