swagger: '2.0'
info:
  title: DORA MCP Server
  description: Model Context Protocol server for DORA (Digital Object Repository for Academia) publications. Search scientific publications across titles, abstracts, authors, and metadata fields.
  version: 1.0.0
host: your-app-name.fly.dev
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /mcp:
    post:
      summary: DORA Publications Search Server
      description: MCP server for searching DORA publications using JSON-RPC 2.0 protocol
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              jsonrpc:
                type: string
                enum:
                  - '2.0'
                description: JSON-RPC version
              id:
                type: integer
                description: Request ID
              method:
                type: string
                enum:
                  - initialize
                  - tools/list
                  - tools/call
                description: MCP method to call
              params:
                type: object
                description: Method parameters
      responses:
        '200':
          description: JSON-RPC 2.0 response
          schema:
            type: object
            properties:
              jsonrpc:
                type: string
              id:
                type: integer
              result:
                type: object
              error:
                type: object
