swagger: '2.0'
info:
  title: DORA Publications MCP Server
  description: Model Context Protocol server for searching DORA (Digital Object Repository for Academia) scientific publications
  version: 1.0.0
host: dora-mcp-xrtnba.fly.dev
basePath: /
schemes:
  - https
paths:
  /mcp:
    get:
      summary: Get MCP Server Information
      description: Returns information about the MCP server and available tools
      operationId: GetMCPInfo
      responses:
        '200':
          description: Server information and available tools
    post:
      summary: DORA Publications Search Server
      description: MCP Streamable endpoint for searching scientific publications
      operationId: InvokeMCP
      x-ms-agentic-protocol: mcp-streamable-1.0
      responses:
        '200':
          description: Success
securityDefinitions: {}
security: []
