swagger: '2.0'
info:
  title: DORA Publications MCP Server
  description: MCP server for searching DORA (Digital Object Repository for Academia) publications
  version: 1.0.0
host: your-app-name.fly.dev
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: DORA Publications Search Server
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      responses:
        '200':
          description: Success
